# No need for API documentation.
Documentation:
  Enabled: false

AllCops:
  RunRailsCops: true
  Exclude:
    - config/initializers/secret_token.rb
    - bin/**/*
    - db/schema.rb
    - db/migrate/*.rb
    - lib/templates/rspec/**/*
    - Guardfile
    - db/seeds/private/**/*

MethodLength:
  Exclude:
    - spec/support/basic_shop.rb

AbcSize:
  Exclude:
    - spec/support/basic_shop.rb
