# No need for API documentation.
Documentation:
  Enabled: false

AllCops:
  Exclude:
    - config/initializers/secret_token.rb
    - bin/**/*
    - db/**/*
    - Guardfile

MethodLength:
  Exclude:
    - spec/support/basic_shop.rb

AbcSize:
  Exclude:
    - spec/support/basic_shop.rb