default: &default
  adapter: postgresql
  encoding: unicode

  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  host: localhost
  database: lychee_development

test:
  <<: *default
  host: localhost
  database: lychee_test

# DATABASE_URL="postgres://user:pass@localhost/database-name"
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
